service: events 

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

functions:
  create:
    handler: events/create.create
    events:
      - http:
          path: events
          method: post
          cors: true
  list:
    handler: events/list.list
    events:
      - http:
          path: events
          method: get
          cors: true
  search:
    handler: events/search.search
    events:
      - http:
          path: events/{id}
          method: get
          cors: true
  update:
    handler: events/update.update
    events:
      - http:
          path: events/{id}
          method: put
          cors: true
  delete:
    handler: events/delete.delete
    events:
      - http:
          path: events/{id}
          method: delete
          cors: true
          
resources:
  Resources:
    eventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LD_EVENTS
        AttributeDefinitions:
          - AttributeName: EVENT_ID
            AttributeType: S
        KeySchema:
          - AttributeName: EVENT_ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

        