service: rsvp

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "arn:aws:ses:us-west-2:079985610213:identity/mbenavente77@gmail.com"

functions:
  create:
    handler: functions/create.create
    events:
      - http:
          path: rsvp
          method: post
          cors: true
  list:
    handler: functions/list.list
    events:
      - http:
          path: rsvp
          method: get
          cors: true
  confirmationEmail:
    handler: functions/confirmationEmail.insert
    events:
      - stream: arn:aws:dynamodb:us-west-2:079985610213:table/LD_RSVP/stream/2017-04-23T19:31:31.825

resources:
  Resources:
    eventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LD_RSVP
        AttributeDefinitions:
          - AttributeName: RSVP_ID
            AttributeType: S 
        KeySchema:
          - AttributeName: RSVP_ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES