/*  
    This is the JavaScript that allows the webpage to act as the API Client. 
    It gets the data from the search bar and sends it to the API Gateway, which will 
    then trigger the Lambda Function (EventsByID.js) to query the DynamoDB table for
    the record with the value provided in the search bar.
*/
/*
var dataResult;
$(document).ready(function() {

    console.log("Search function has loaded");
    //Initializes the SDK generated by API Gateway 
    var apigClient = apigClientFactory.newClient();
    $("form[name='searchForm1']").submit(function(event) {
        console.log("A day submission has ben made");
        //Get the form data
        var formData = {
            'DAY_OF_WEEK' : $('input[name=DOW_sub]').val()
        };

        var params = {
            //This is where any head, path or querystring request params go. The key is the parameter named as defined in the API
            'DAY_OF_WEEK' :  $('input[name=DOW_sub]').val()
        };

        var body = {
        };
        
        var additionalParams = {
             headers: {
             },
             queryParams: {
                 'DAY_OF_WEEK' : $('input[name=DOW_sub]').val()
             }
        };

        apigClient.eventsbydayGet(params, body, additionalParams) 
            .then(function(result){
              
                dataResult = JSON.stringify(result.data);
                console.log("Result Data: " +dataResult);
                var resultArray =JSON.parse(dataResult);
                console.log(resultArray);
                console.log(resultArray[0].Items.DAY_OF_WEEK);
                //Console.log("Data result element " + dataResult.Items.EVENT_ID);
                //Console.log("First Array Element: " + resultArray['EVENT_ID']);
                //console.log("Result Data Stringified: " + JSON.stringify(result.data));
                //console.log("Result String Stringified: " + JSON.stringify(resultStr));
                //var resultStr = 'Event ID: <b>'+dataResult.Items.EVENT_ID.N +'</b><br>'
                // +'</b><br>'+'Event Name: <b>'+dataResult.Items.EVENT_NAME+'</b><br>'+'Venue Name: <b>'+dataResult.Items.VENUE_NAME +'</b><br>';
                //console.log("Result string to be displayed: " + resultStr);
                var resultStr = 4;
                //console.log("One Step Further: " + result.data.Items.EVENT_ID.N);
                
                $('#results').html(resultStr); //This sets the Results HTML contents to contain the results from the GET
            }).catch( function(result) {
                console.log('error');
                /*console.log("Result Data Stringified: " + JSON.stringify(result.data));
                console.log(result.data.Items.EVENT_ID);
                console.log(result.data.Items.EVENT_ID);
                console.log("One Step Further: " + result.data.Items.EVENT_ID.N);
               // console.log("Result Data Parsed: " + JSON.parse(result.data)); 
                console.log("Result string to be displayed: " + resultStr);
            });
        
        return false;
    });
}); */

/*  Testing: Lambda Function - Test Event
{
  "body-json": {},
  "params": {
    "path": {},
    "querystring": {
      "DAY_OF_WEEK": "Thursday"
    }
  }
} 
*/