/*  
    This is the JavaScript that allows the webpage to act as the API Client. 
    It gets the data from the search bar and sends it to the API Gateway, which will 
    then trigger the Lambda Function (EventsByID.js) to query the DynamoDB table for
    the record with the value provided in the search bar.
*/
    /* Email validation on front end
    function ValidateEmail(x){  
 	    if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(x)){ 
  	        return (true) 
        } else {return (false)}
    } 

  
    if(ValidateEmail(emailString) === true){
		console.log("Email is valid: " + emailString);
        } else {
	    console.log("!!!INVALID EMAIL!!!: " + emailString);
        } */
/*

var dataResult;
$(document).ready(function() {

    console.log("RSVP function has loaded");
    //Initializes the SDK generated by API Gateway 
    var apigClient = apigClientFactory.newClient({
        accessKey: 'AKIAJX3JUXPMF5ANBMYA',
        secretKey: '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',
    });

    $("form[name='rsvpForm1']").submit(function(event) {
        console.log("A RSVP submission has ben made");
        //Get the form data
        var formData = {
            'emailQS' : $('input[name=EMAIL_sub]').val(),
            'eventidQS' : $('input[name=EVENT_ID_sub]').val()
        };

        var params = {
            //This is where any head, path or querystring request params go. The key is the parameter named as defined in the API
            'emailQS' : $('input[name=EMAIL_sub]').val(),
            'eventidQS' : $('input[name=EVENT_ID_sub]').val()
        };

        var body = {
        };
        
        var additionalParams = {
             headers: {
             },
            queryParams: {
                'emailQS' : $('input[name=EMAIL_sub]').val(),
                'eventidQS' : $('input[name=EVENT_ID_sub]').val()
             }
        };

        apigClient.rsvpPost(params, body, additionalParams) 
            .then(function(result){
                console.log(result.data);
                dataResult = result.data;
                var resultStr = 'You have are now confirmed for the event with ID: <b>'+result.data.Item.eventidQS+'</b><br>'+' You will recieve a confirmation email at: <b>'+result.data.Item.emailQS+'</b><br>'+'Thank you for using our service! <b>';
                console.log(resultStr);
                $('#results').html(resultStr); //This sets the Results HTML contents to contain the results from the GET
            }).catch( function(result) {
                console.log('error');
            });
        
        return false;
    });
});

/*  Testing: Lambda Function - Test Event
{
  "body-json": {},
  "params": {
    "path": {},
    "querystring": {
        "emailQS": "mbenavente77@gmail.com",
        "eventidQS": "101"
    }
  }
}
*/
